### ISSUE TITLE
Reference for `calc_checksum` function

### ISSUE THREAD

**Issue by merkys** [dkratzert/FinalCif#3]
While looking at the code, I noticed `calc_checksum` function to calculate SHELX cheksums:
https://github.com/dkratzert/FinalCif/blob/608217753a04fe314cd44673c1b70bf4e30b9e7d/cif/cif_file_io.py#L386
I have applied this code to check included SHELX files in the COD, and found out that ~6% of the COD CIF files with SHELX data have checksum mismatches, originating in the unmodified published CIF files (for example, https://pubs.acs.org/doi/suppl/10.1021/acs.orglett.6b02703/suppl_file/ol6b02703_si_003.cif).

Thus I am interested in the reference for this function, as I was unable to find SHELX checksums explained in SHELX manuals. Could it be that checksum algorithm has changed at some SHELX version? This could explain ~6% mismatching SHELX data in the COD.

**Comment by dkratzert** [comment]
This code was posted on the Bruker-users mailing list by Berthold Stöger a while ago. (I should add a dedication)
You could check the correctness with the shredcif tool of George Sheldrick. https://shelx.uni-goettingen.de/download.php
It expects a cif file as input and writes out the containing .res and .hkl file. The test result of the checksum is printed on the screen.

**Comment by merkys** [comment]
Thank you for prompt response. I have checked the aforementioned CIF file with `shredcif` and got the warning about the checksum mismatch, just as expected. So the checksum verification code seems OK. Thanks!

**Comment by dkratzert** [comment]
The checksums in CIF files are remarkably often incorrect. That was one of the main reasons why I began with Finalcif 😊
