### ISSUE TITLE
how add absorption correction entry in the template of multiple cif table？ 

### ISSUE THREAD

**Issue by skipskipthree** [dkratzert/FinalCif#78]
Adding an absorption correction entry to a report with multiple cif data, the template for a single cif data can be modified, but I didn't find a template for multiple cif data reports.

**Comment by dkratzert** [comment]
Unfortunately, there is currently no possibility to use a custom template with multi-CIF files.  How exactly do you would like to have it? Can you give a more specific example?

**Comment by dkratzert** [comment]
This is related to #73

**Comment by skipskipthree** [comment]
Thank you, a lot.  For example, when I merge two .cif files into one file, then I use findcif to generate a report. I want to add the absorption correction data in the red column. How can I modify the template?
![5b88deb56cc2080a9b0eeb053319fd0](https://github.com/dkratzert/FinalCif/assets/33718851/3c2c8adf-e04b-4ff6-bc85-7d0e1d43ef50)
